version: '3'
services:
  user_server:
    build:
      context: ./US
    ports:
      - "8080:8080"
    networks:
      - app-network

  fibonacci_server:
    build:
      context: ./FS
    ports:
      - "9090:9090"
    networks:
      - app-network

  auth_server:
    build:
      context: ./AS
    ports:
      - "53533:53533/udp"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
